version: "3.9"

volumes:
  finance-bot-postgresql-volume:
    name: use-bot-postgresql

services:
  finance-bot-postgresql:
    container_name: use-bot-postgresql
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=use-bot-db
      - POSTGRES_USER=bot-user
      - POSTGRES_PASSWORD=bot-user-pass
    volumes:
      - finance-bot-postgresql-volume:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 300m