version: "3.9"

volumes:
  finance-bot-postgresql-volume:
    name: use-bot-postgresql

services:
  use-bot-postgresql:
    container_name: use-bot-postgresql
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=use-bot-db
      - POSTGRES_USER=bot-user
      - POSTGRES_PASSWORD=bot-user-pass
    volumes:
      - finance-bot-postgresql-volume:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 300m
  telegram-bot:
    container_name: telegram-bot
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://use-bot-postgresql:5432/use-bot-db
      - SPRING_DATASOURCE_USERNAME=bot-user
      - SPRING_DATASOURCE_PASSWORD=bot-user-pass
    ports:
      - "8080:8080"
    depends_on:
      - use-bot-postgresql