package com.study.bot.state.stage;

public enum AdminStage {
    NONE,
    CREATE_PARAGRAPH,
    ADD_IMAGE_TO_PARAGRAPH,
    ASK_IMAGE_URL,
    ASK_IMAGE_ORDINAL,
    GET_ALL_PARAGRAPHS,
    CREATE_SECTION,
    CHOOSE_SECTION,
    GET_ALL_SECTIONS,
    ASK_TEST_IMAGE_URL,
    ASK_TEST_ANSWER1,
    ASK_TEST_ANSWER2,
    ASK_TEST_ANSWER3,
    ASK_TEST_ANSWER4,
    ASK_TEST_CORRECT_ANSWER,
    GET_STUDENTS_PROGRESS
}
