package com.study.bot.state.stage;

public enum UserStage {
    NONE,
    CONFIRM_ACTION,
    GET_PARAGRAPH,
    SELECT_PARAGRAPH,
    VIEW_IMAGES,
    GET_SECTION,
    SELECT_SECTION,
    START_TEST,
    ANSWER_TEST,
    ANOTHER_TEST,
    VIEW_SECOND_PART_IMAGE,
    ANSWER_SECOND_PART_IMAGE
}
